### ISSUE TITLE
Possible bugs in Differencer.java

### ISSUE THREAD

**Issue by javipeg** [ReinoutStevens/ChangeNodes#1]
Found some possible bugs at Differencer.java

lines:

```
166: return -> continue
```

(otherwise the code will stop comparing the reamaining node properties once two of them are found equally null)

```
311: "deletes" is never initialised
```

(foreach loop is never entered)

**Comment by javipeg** [comment]
Ok. I re-checked and the `deletes` list gets filled up in the next iterations.

However the break jump at line 317 bothers me ...
I wrote this slightly different version instead. Starting at line 308

```
if(node != null && !leftMatchingPrime.containsKey(node)){
    boolean parentAlreadyDeleted = false;
    Iterator deletesIterator = deletes.iterator();
    while(deletesIterator.hasNext()){
        Delete delete = (Delete) deletesIterator.next();
        HierarchicalEntityState potentialParent = delete.getAffectedNode();
        HierarchicalEntityState parent = node;
        while(!parentAlreadyDeleted && parent != null){
            if(parent.equals(potentialParent)){
                parentAlreadyDeleted = true;
            } else {
                parent = parent.getParentNode();
            }
        }
    }
    if(!parentAlreadyDeleted){
        Delete delete = new Delete(getOriginal(node), node);
        deletes.add(delete);
    }
}
```

Feels better without the break jump.

**Comment by ReinoutStevens** [comment]
Line 166 does appear to be a bug and has been fixed.
The delete code should be correct, although your version seems to be more readable. I'll integrate it.
Thanks for the feedback

**Comment by javipeg** [comment]
Cool! Thanks. Glad to help!
